version: "3.8"

networks:
  my_bridge_tybscit01:
    driver: bridge

services:
  java_app:
    build: .
    container_name: java_app
    networks:
      - my_bridge_tybscit01

  toolbox:
    image: busybox:latest
    container_name: toolbox
    command: sleep 3600
    networks:
      my_bridge_tybscit01:
        aliases:
          - helper